---
chartVersion: "0.11.1"
version: "4.8.29"
license:
  name: "Premium"
  assignee: "Nemerosa BV"
  active: true
  validUntil: null
  maxProjects: 0
domain: "nemerosa.net"
application: |
  ontrack:
    config:
      extension:
        notifications:
          enabled: true

